### ISSUE TITLE
404

### ISSUE THREAD

**Issue by cortesimone** [osmItalia/estratti-locali-openstreetmap#15]
a 404 error handler is missing

see http://osm-estratti.wmflabs.org/estratti/dferufuherhufiure

**Comment by sabas** [comment]
The function which intercepts the 404 is this one https://github.com/osmItalia/estratti-locali-openstreetmap/blob/master/html/index.php#L149

Should we implement a page?

**Comment by cortesimone** [comment]
yes, this is what I meant by that

**Comment by sabas** [comment]
Simply shows 404 into the template now
