### ISSUE TITLE
Proposta di modifica del testo

### ISSUE THREAD

**Issue by aborruso** [osmItalia/estratti-locali-openstreetmap#17]
In pagine come [questa](http://osm-estratti.wmflabs.org/estratti/Sicilia/Palermo/Palermo) si legge:

> Tutti i file usano il sistema di riferimento WGS84.

Il WGS84 è però più propriamente un datum. Vi propongo di trasformarlo in:

> Il sistema di riferimento di tutti i layer contenuti nei file è [EPSG:4326](http://epsg.io/4326).

Lasciando il link a epsg.io (o simili).

Grazie per l'attenzione e grazie per quello che fate

**Comment by sabas** [comment]
Si può fare, basta cambiare DESC_DOWNLOAD_2 nei json delle stringhe.
Per italiano ed inglese lo so fare.
Come si tradurrà in tedesco?

**Comment by sabas** [comment]
Fatto, meglio tardi che mai :)
