### ISSUE TITLE
Update project description link

### ISSUE THREAD

**Issue by tyrasd** [osmItalia/estratti-locali-openstreetmap#7]
The reporistory description still links to http://osm-toolserver-italia.wmflabs.org/estratti/ which doesn't have the most up-to-date version of the UI and extracts. It should read http://osm-estratti.wmflabs.org/estratti/, I guess?

**Comment by sabas** [comment]
I put estratti.openstreetmap.it as new link, at least should be future proof :-)

Thanks Martin!
